#!/bin/bash

OUTPUT=huetten.gpx

cat > "$OUTPUT" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1" creator="Beispiel" xmlns="http://www.topografix.com/GPX/1/1">
EOF

grep -R 'mlat=' [0-9]* | \
    sort | \
    sed -n 's/^[0-9][0-9]-\([^:]*\)\/text:.*mlat=\([0-9.-]*\).*mlon=\([0-9.-]*\).*/ <wpt lat="\2" lon="\3"> <name>\1<\/name> <\/wpt> /p' >> "$OUTPUT"

cat >> "$OUTPUT" <<EOF
</gpx>
EOF

xmlformat -i "$OUTPUT"
